version: '3.7'

networks:
  scala-blockchain-network:

services:
  seed:
    networks:
      - scala-blockchain-network
    image: xammel/scala-blockchain
    volumes:
      - ~/dev/scala/blockchain-messaging-app:/tmp/scala-blockchain
    ports:
      - '2552:2552'
      - '8000:8080'
    environment:
      SERVER_IP: 0.0.0.0
      CLUSTER_IP: seed
      CLUSTER_SEED_IP: seed
      SCALACHAIN_PERSISTENCE_DIR: '/persistence/seed/journal'
      SCALACHAIN_SNAPSHOTS_DIR: '/persistence/seed/snapshots'
    command: ["local", "/tmp/scala-blockchain"]

  node1:
    networks:
      - scala-blockchain-network
    image: xammel/scala-blockchain
    volumes:
      - ~/dev/scala/blockchain-messaging-app:/tmp/scala-blockchain
    ports:
      - '8001:8080'
    environment:
      SERVER_IP: 0.0.0.0
      CLUSTER_IP: node1
      CLUSTER_PORT: 1600
      CLUSTER_SEED_IP: seed
      CLUSTER_SEED_PORT: 2552
      SCALACHAIN_NODE_ID: node1
      SCALACHAIN_PERSISTENCE_DIR: '/persistence/node1/journal'
      SCALACHAIN_SNAPSHOTS_DIR: '/persistence/node1/snapshots'
    command: ["local", "/tmp/scala-blockchain"]

  node2:
    networks:
      - scala-blockchain-network
    image: xammel/scala-blockchain
    volumes:
      - ~/dev/scala/blockchain-messaging-app:/tmp/scala-blockchain
    ports:
      - '8002:8080'
    environment:
      SERVER_IP: 0.0.0.0
      CLUSTER_IP: node2
      CLUSTER_PORT: 1600
      CLUSTER_SEED_IP: seed
      CLUSTER_SEED_PORT: 2552
      SCALACHAIN_NODE_ID: node2
      SCALACHAIN_PERSISTENCE_DIR: '/persistence/node2/journal'
      SCALACHAIN_SNAPSHOTS_DIR: '/persistence/node2/snapshots'
    command: ["local", "/tmp/scala-blockchain"]